### ISSUE TITLE
Installation problem with npm -g i forward.js  on windows

### ISSUE THREAD

**Issue by JiaJiaJiang** [sjitech/nodejs-port-forward#1]
Aftering installing using `npm i forward -g` on windows, an extra `forward.js` file will be created in user\AppData\Roaming\npm.
And the `forward.js ***` command will open the `forward.js` file created by npm.

**Comment by jjqq2013** [comment]
Hi, thank you for reporting the issue. You can try forward.js.cmd

**Comment by JiaJiaJiang** [comment]
I have deleted the .js file and solved the problem.
So is this a bug or a feature?

**Comment by jjqq2013** [comment]
This is a feature of npm.

you might have not set explorer to show extension name of file, the file
you deleted might be forward.js.cmd!

Npm will install a forward.js.cmd in appdata/npm/xxxxx/bin as a launch
helper.

If you use npm to install it then you can just run forward.js.cmd without
specify node.exe manually. Or you can ignore it and just run “node.exe
xxxxxxxforward.js.

Anyway, this is just a one script utility, as long as you hold the actual
forward.js, you can run node.exe and pass the file path to it.

You can check the package.json where noted the run command is forward.js.

Originally, In linux, the forward.js can be directly run after npm install
-g ...
,  this is because forward.js defined “#/bin/env  node” in first line so
linux will use the command  as script runner.

But when in windows, It does not recognize the first line and have no such
exe file neither. So, npm will create a forwadr.js.cmd to as a wrapper to
help you start nodejs and pass forward.js to it.

That is all the story.

2018年2月27日(火) 18:05 罗佳 <notifications@github.com>:

**Comment by JiaJiaJiang** [comment]
I think I have found out the problem.
Npm creates a `forward.js.cmd` and a `forward.js` for cmd and powershell, so when I use the command `forward.js`, windows mathes the js file first and opens the js file.

Contents of the file `forward.js` is 
```
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/node_modules/forward.js/forward.js" "$@"
  ret=$?
else 
  node  "$basedir/node_modules/forward.js/forward.js" "$@"
  ret=$?
fi
exit $ret
```
and contents of the file `forward.js.cmd` is 
```
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\node_modules\forward.js\forward.js" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\node_modules\forward.js\forward.js" %*
)
```

So the reason is that the command has a .js extension.

**Comment by jjqq2013** [comment]
thank you.

That forward.js in npm bin is not for windows user, it is autoncreated by
npm for linux or cygwin, mingw...

Windows user should append a .cmd, you can find these info in npm docs.

2018年2月27日(火) 20:44 罗佳 <notifications@github.com>:

**Comment by JiaJiaJiang** [comment]
Oh, I see. Thanks for explaining that.
So the bin name caused the ambiguity. May you change it?
You can ignore this advice and just close the issue now.

**Comment by jjqq2013** [comment]
This is a feature of npm, not created by me, so I can not change it.  I will close this issue.
